// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnoQSJQXlurTWg1VUHsns5JB22ad4THsY',
    appId: '1:695206137386:web:f5327738a594ad579f7d53',
    messagingSenderId: '695206137386',
    projectId: 'match-score-store',
    authDomain: 'match-score-store.firebaseapp.com',
    storageBucket: 'match-score-store.appspot.com',
    measurementId: 'G-9TC0FLCE92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANFaX65Yg8HoKHV48woChjs0d2Z-R-PLk',
    appId: '1:695206137386:android:e710046b999692679f7d53',
    messagingSenderId: '695206137386',
    projectId: 'match-score-store',
    storageBucket: 'match-score-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDka_bV69i2sq9Xrrn7Q_QyXSsD4uoZbF8',
    appId: '1:695206137386:ios:8c5592c202bee1459f7d53',
    messagingSenderId: '695206137386',
    projectId: 'match-score-store',
    storageBucket: 'match-score-store.appspot.com',
    iosBundleId: 'com.example.matchScore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDka_bV69i2sq9Xrrn7Q_QyXSsD4uoZbF8',
    appId: '1:695206137386:ios:aba720ff281bd9ab9f7d53',
    messagingSenderId: '695206137386',
    projectId: 'match-score-store',
    storageBucket: 'match-score-store.appspot.com',
    iosBundleId: 'com.example.matchScore.RunnerTests',
  );
}
